name: Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v

      - name: Push to prod
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.PROD_HOST }}
          USERNAME: ${{ secrets.PROD_USER }}
          PORT: ${{ secrets.PROD_PORT }}
          PASSWORD: ${{ secrets.PROD_PASSWORD }}
        with:
          source: "beansports-api"
          target: "/home/beansports/bin/"

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          USERNAME: ${{ secrets.PROD_USER }}
          PORT: ${{ secrets.PROD_PORT }}
          PASSWORD: ${{ secrets.PROD_PASSWORD }}
          script: ls
